/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MarketRouteImport } from './routes/market'
import { Route as FertilizerRouteImport } from './routes/fertilizer'
import { Route as DiseaseRouteImport } from './routes/disease'
import { Route as CropRouteImport } from './routes/crop'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMandiRouteImport } from './routes/api/mandi'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const FertilizerRoute = FertilizerRouteImport.update({
  id: '/fertilizer',
  path: '/fertilizer',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseaseRoute = DiseaseRouteImport.update({
  id: '/disease',
  path: '/disease',
  getParentRoute: () => rootRouteImport,
} as any)
const CropRoute = CropRouteImport.update({
  id: '/crop',
  path: '/crop',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMandiRoute = ApiMandiRouteImport.update({
  id: '/api/mandi',
  path: '/api/mandi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/crop': typeof CropRoute
  '/disease': typeof DiseaseRoute
  '/fertilizer': typeof FertilizerRoute
  '/market': typeof MarketRoute
  '/profile': typeof ProfileRoute
  '/api/mandi': typeof ApiMandiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/crop': typeof CropRoute
  '/disease': typeof DiseaseRoute
  '/fertilizer': typeof FertilizerRoute
  '/market': typeof MarketRoute
  '/profile': typeof ProfileRoute
  '/api/mandi': typeof ApiMandiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/crop': typeof CropRoute
  '/disease': typeof DiseaseRoute
  '/fertilizer': typeof FertilizerRoute
  '/market': typeof MarketRoute
  '/profile': typeof ProfileRoute
  '/api/mandi': typeof ApiMandiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/crop'
    | '/disease'
    | '/fertilizer'
    | '/market'
    | '/profile'
    | '/api/mandi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/crop'
    | '/disease'
    | '/fertilizer'
    | '/market'
    | '/profile'
    | '/api/mandi'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/crop'
    | '/disease'
    | '/fertilizer'
    | '/market'
    | '/profile'
    | '/api/mandi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  CropRoute: typeof CropRoute
  DiseaseRoute: typeof DiseaseRoute
  FertilizerRoute: typeof FertilizerRoute
  MarketRoute: typeof MarketRoute
  ProfileRoute: typeof ProfileRoute
  ApiMandiRoute: typeof ApiMandiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fertilizer': {
      id: '/fertilizer'
      path: '/fertilizer'
      fullPath: '/fertilizer'
      preLoaderRoute: typeof FertilizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disease': {
      id: '/disease'
      path: '/disease'
      fullPath: '/disease'
      preLoaderRoute: typeof DiseaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop': {
      id: '/crop'
      path: '/crop'
      fullPath: '/crop'
      preLoaderRoute: typeof CropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mandi': {
      id: '/api/mandi'
      path: '/api/mandi'
      fullPath: '/api/mandi'
      preLoaderRoute: typeof ApiMandiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  CropRoute: CropRoute,
  DiseaseRoute: DiseaseRoute,
  FertilizerRoute: FertilizerRoute,
  MarketRoute: MarketRoute,
  ProfileRoute: ProfileRoute,
  ApiMandiRoute: ApiMandiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
