/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MarketRouteImport } from './routes/market'
import { Route as DiseaseRouteImport } from './routes/disease'
import { Route as CropRouteImport } from './routes/crop'
import { Route as IndexRouteImport } from './routes/index'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseaseRoute = DiseaseRouteImport.update({
  id: '/disease',
  path: '/disease',
  getParentRoute: () => rootRouteImport,
} as any)
const CropRoute = CropRouteImport.update({
  id: '/crop',
  path: '/crop',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crop': typeof CropRoute
  '/disease': typeof DiseaseRoute
  '/market': typeof MarketRoute
  '/profile': typeof ProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crop': typeof CropRoute
  '/disease': typeof DiseaseRoute
  '/market': typeof MarketRoute
  '/profile': typeof ProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crop': typeof CropRoute
  '/disease': typeof DiseaseRoute
  '/market': typeof MarketRoute
  '/profile': typeof ProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/crop' | '/disease' | '/market' | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/crop' | '/disease' | '/market' | '/profile'
  id: '__root__' | '/' | '/crop' | '/disease' | '/market' | '/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CropRoute: typeof CropRoute
  DiseaseRoute: typeof DiseaseRoute
  MarketRoute: typeof MarketRoute
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disease': {
      id: '/disease'
      path: '/disease'
      fullPath: '/disease'
      preLoaderRoute: typeof DiseaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop': {
      id: '/crop'
      path: '/crop'
      fullPath: '/crop'
      preLoaderRoute: typeof CropRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CropRoute: CropRoute,
  DiseaseRoute: DiseaseRoute,
  MarketRoute: MarketRoute,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
